import { z } from "zod";

export const eventBiodata = z.object({
  type: z.enum([
    "data_mempelai",
    "list_teapai",
    "list_corsages",
    "list_makeup",
    "list_transport",
    "list_foto",
    "event_layout",
  ]),
  mempelai_notes: z.optional(z.string()),
  mempelai_pic: z.optional(z.string()),
  mempelai_contact_number: z.optional(z.string()),
  teapai_bride_name: z.optional(z.string()),
  teapai_bride_side: z.optional(z.string()),
  teapai_bride_note: z.optional(z.string()),
  teapai_groom_name: z.optional(z.string()),
  teapai_groom_side: z.optional(z.string()),
  teapai_groom_note: z.optional(z.string()),
  makeup_name: z.optional(z.string()),
  makeup_mua: z.optional(z.string()),
  makeup_teamnr: z.optional(z.string()),
  makeup_retouch: z.optional(z.string()),
  makeup_room: z.optional(z.string()),
  makeup_note: z.optional(z.string()),
  corsages_name: z.optional(z.string()),
  corsages_note: z.optional(z.string()),
  transport_name: z.optional(z.string()),
  transport_driver: z.optional(z.string()),
  transport_vehicle: z.optional(z.string()),
  transport_platenr: z.optional(z.string()),
  transport_notes: z.optional(z.string()),
  event_layout: z.optional(z.string()),
  foto_groom: z.optional(z.string()),
  foto_groom_note: z.optional(z.string()),
  foto_bride: z.optional(z.string()),
  foto_bride_note: z.optional(z.string()),
  foto_penjemputan: z.optional(z.string()),
  foto_penjemputan_note: z.optional(z.string()),
  order_nr: z.optional(z.number()),
});
